---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: aade/pythonapp:0.0.0
          ports:
            - containerPort: 80
          resources: 
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: python

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-python
spec:
  rules:
  - host: py.10-0-10-10.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python
            port:
              number: 80
  ingressClassName: nginx